import { existsSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { resolve as resolvePath } from 'node:path'
import { resolveDeployImageRef } from './images.js'
import type { BuildTarget, TargetScaffoldFile, TargetScaffoldPlan } from './types.js'

const DEFAULT_FLY_PRIMARY_REGION = 'sea'
const DEFAULT_K8S_STORAGE_SIZE = '5Gi'

export function createTargetScaffoldPlan(options: {
  readonly target: BuildTarget
  readonly cwd: string
  readonly appName: string
  readonly imageTag: string
  readonly environment?: NodeJS.ProcessEnv
}): TargetScaffoldPlan {
  const deployImageRef = resolveDeployImageRef({
    target: options.target,
    appName: options.appName,
    imageTag: options.imageTag,
    environment: options.environment,
  })
  const files = renderTargetScaffoldFiles({
    target: options.target,
    cwd: options.cwd,
    appName: options.appName,
    imageTag: options.imageTag,
    deployImageRef,
    environment: options.environment ?? process.env,
  })

  for (const file of files) {
    if (existsSync(file.filePath)) {
      throw new Error(`refusing to overwrite existing scaffold file: ${file.filePath}`)
    }
  }

  const primary = files[0]
  return {
    target: options.target,
    fileName: primary.fileName,
    filePath: primary.filePath,
    contents: primary.contents,
    files,
  }
}

export async function writeTargetScaffold(plan: TargetScaffoldPlan): Promise<void> {
  for (const file of plan.files) {
    await writeFile(file.filePath, file.contents, { flag: 'wx' })
  }
}

function renderTargetScaffoldFiles(options: {
  readonly target: BuildTarget
  readonly cwd: string
  readonly appName: string
  readonly imageTag: string
  readonly deployImageRef: string
  readonly environment: NodeJS.ProcessEnv
}): readonly TargetScaffoldFile[] {
  switch (options.target) {
    case 'cloudflare':
      return renderCloudflareScaffold(options)
    case 'docker':
      return [
        targetFile(options.cwd, 'Dockerfile', renderDockerfileScaffold(options.imageTag)),
      ]
    case 'docker-compose':
      return [
        targetFile(
          options.cwd,
          'docker-compose.yml',
          renderDockerComposeScaffold(options.appName, options.deployImageRef),
        ),
      ]
    case 'fly':
      return [
        targetFile(
          options.cwd,
          'fly.toml',
          renderFlyScaffold(options.appName, options.deployImageRef, options.environment),
        ),
      ]
    case 'k8s':
      return [
        targetFile(
          options.cwd,
          'k8s.yaml',
          renderK8sScaffold(options.appName, options.deployImageRef, options.environment),
        ),
      ]
  }
}

function renderCloudflareScaffold(options: {
  readonly cwd: string
  readonly appName: string
  readonly imageTag: string
  readonly deployImageRef: string
}): readonly TargetScaffoldFile[] {
  const primaryPath = resolvePath(options.cwd, 'wrangler.toml')
  if (options.deployImageRef !== options.imageTag) {
    return [
      {
        fileName: 'wrangler.toml',
        filePath: primaryPath,
        contents: [
          '# Generated by `fireline deploy --to cloudflare-containers`.',
          '# This path assumes the image is already reachable from Cloudflare Containers.',
          `name = "${options.appName}"`,
          `compatibility_date = "${new Date().toISOString().slice(0, 10)}"`,
          '',
          '[observability.logs]',
          'enabled = true',
          '',
          '[[containers]]',
          `image = "${options.deployImageRef}"`,
          '',
          '[vars]',
          `FIRELINE_NAME = "${options.appName}"`,
          '',
        ].join('\n'),
      },
    ]
  }

  return [
    {
      fileName: 'wrangler.toml',
      filePath: primaryPath,
      contents: [
        '# Generated by `fireline deploy --to cloudflare-containers`.',
        '# Wrangler will publish the wrapped quickstart image from Dockerfile.fireline.',
        `name = "${options.appName}"`,
        `compatibility_date = "${new Date().toISOString().slice(0, 10)}"`,
        '',
        '[observability.logs]',
        'enabled = true',
        '',
        '[[containers]]',
        'image = "./Dockerfile.fireline"',
        '',
        '[vars]',
        `FIRELINE_NAME = "${options.appName}"`,
        '',
      ].join('\n'),
    },
    targetFile(options.cwd, 'Dockerfile.fireline', renderDockerfileScaffold(options.imageTag)),
  ]
}

function renderDockerfileScaffold(imageTag: string): string {
  return [
    '# Scaffold only. Reuses the Fireline hosted image built by `fireline build`.',
    `FROM ${imageTag}`,
    '',
    'EXPOSE 4440 7474',
    '',
  ].join('\n')
}

function renderDockerComposeScaffold(appName: string, imageRef: string): string {
  return [
    'services:',
    '  fireline:',
    `    image: ${imageRef}`,
    '    restart: unless-stopped',
    '    environment:',
    '      FIRELINE_NAME: ' + quoteYaml(appName),
    '      FIRELINE_PORT: "4440"',
    '      FIRELINE_STREAMS_PORT: "7474"',
    '      DS_STORAGE__MODE: file-durable',
    '      DS_STORAGE__DATA_DIR: /var/lib/fireline/durable-streams',
    '    ports:',
    '      - "4440:4440"',
    '      - "7474:7474"',
    '    healthcheck:',
    '      test: ["CMD", "/usr/local/bin/healthcheck-http", "http://127.0.0.1:4440/healthz", "http://127.0.0.1:7474/healthz"]',
    '      interval: 30s',
    '      timeout: 5s',
    '      retries: 3',
    '      start_period: 20s',
    '    volumes:',
    '      - fireline-data:/var/lib/fireline',
    '',
    'volumes:',
    '  fireline-data:',
    '',
  ].join('\n')
}

function renderFlyScaffold(
  appName: string,
  imageRef: string,
  environment: NodeJS.ProcessEnv,
): string {
  const primaryRegion = environment.FIRELINE_FLY_PRIMARY_REGION?.trim() || DEFAULT_FLY_PRIMARY_REGION
  const flyVolume = environment.FIRELINE_FLY_VOLUME?.trim()
  const lines = [
    '# Generated by `fireline deploy --to fly`.',
    '# Add a persistent volume at /var/lib/fireline to keep durable-streams data across restarts.',
    `app = "${appName}"`,
    `primary_region = "${primaryRegion}"`,
    '',
    '[build]',
    `  image = "${imageRef}"`,
    '',
    '[env]',
    `  FIRELINE_NAME = "${appName}"`,
    '',
    '[http_service]',
    '  internal_port = 4440',
    '  force_https = true',
    '  auto_start_machines = true',
    '  auto_stop_machines = "off"',
    '  min_machines_running = 1',
    '',
    '  [[http_service.checks]]',
    '    grace_period = "20s"',
    '    interval = "15s"',
    '    method = "GET"',
    '    path = "/healthz"',
    '    timeout = "5s"',
  ]

  if (flyVolume) {
    lines.push('', '[[mounts]]', `  source = "${flyVolume}"`, '  destination = "/var/lib/fireline"')
  } else {
    lines.push('', '# To persist durable-streams data, set FIRELINE_FLY_VOLUME=<volume-name> before scaffolding.')
  }

  lines.push('')
  return lines.join('\n')
}

function renderK8sScaffold(
  appName: string,
  imageRef: string,
  environment: NodeJS.ProcessEnv,
): string {
  const storageClass = environment.FIRELINE_K8S_STORAGE_CLASS?.trim()
  const storageSize = environment.FIRELINE_K8S_STORAGE_SIZE?.trim() || DEFAULT_K8S_STORAGE_SIZE
  const imagePullSecret = environment.FIRELINE_K8S_IMAGE_PULL_SECRET?.trim()

  const pvcStorageClassLines = storageClass
    ? [`  storageClassName: ${storageClass}`]
    : []
  const imagePullSecretLines = imagePullSecret
    ? ['      imagePullSecrets:', `        - name: ${imagePullSecret}`]
    : []

  return [
    '# Generated by `fireline deploy --to k8s`.',
    '# Set FIRELINE_DEPLOY_IMAGE or FIRELINE_DEPLOY_REGISTRY before deploying to a remote cluster.',
    'apiVersion: v1',
    'kind: PersistentVolumeClaim',
    'metadata:',
    `  name: ${appName}-data`,
    'spec:',
    '  accessModes:',
    '    - ReadWriteOnce',
    ...pvcStorageClassLines,
    '  resources:',
    '    requests:',
    `      storage: ${storageSize}`,
    '---',
    'apiVersion: apps/v1',
    'kind: Deployment',
    'metadata:',
    `  name: ${appName}`,
    'spec:',
    '  replicas: 1',
    '  selector:',
    '    matchLabels:',
    `      app: ${appName}`,
    '  template:',
    '    metadata:',
    '      labels:',
    `        app: ${appName}`,
    '    spec:',
    ...imagePullSecretLines,
    '      containers:',
    `        - name: ${appName}`,
    `          image: ${imageRef}`,
    '          ports:',
    '            - containerPort: 4440',
    '            - containerPort: 7474',
    '          env:',
    `            - name: FIRELINE_NAME`,
    `              value: "${appName}"`,
    '            - name: FIRELINE_PORT',
    '              value: "4440"',
    '            - name: FIRELINE_STREAMS_PORT',
    '              value: "7474"',
    '            - name: DS_STORAGE__MODE',
    '              value: "file-durable"',
    '            - name: DS_STORAGE__DATA_DIR',
    '              value: "/var/lib/fireline/durable-streams"',
    '          volumeMounts:',
    '            - mountPath: /var/lib/fireline',
    `              name: ${appName}-data`,
    '          readinessProbe:',
    '            httpGet:',
    '              path: /healthz',
    '              port: 4440',
    '          livenessProbe:',
    '            httpGet:',
    '              path: /healthz',
    '              port: 4440',
    '      volumes:',
    `        - name: ${appName}-data`,
    '          persistentVolumeClaim:',
    `            claimName: ${appName}-data`,
    '---',
    'apiVersion: v1',
    'kind: Service',
    'metadata:',
    `  name: ${appName}`,
    'spec:',
    '  selector:',
    `    app: ${appName}`,
    '  ports:',
    '    - name: acp',
    '      port: 80',
    '      targetPort: 4440',
    '    - name: streams',
    '      port: 7474',
    '      targetPort: 7474',
    '',
  ].join('\n')
}

function quoteYaml(value: string): string {
  return JSON.stringify(value)
}

function targetFile(cwd: string, fileName: string, contents: string): TargetScaffoldFile {
  return {
    fileName,
    filePath: resolvePath(cwd, fileName),
    contents,
  }
}
