/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RuntimesTypeNameRouteImport } from './routes/runtimes.$typeName'
import { Route as RuntimesTypeNameInstanceNameRouteImport } from './routes/runtimes.$typeName.$instanceName'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as SettingsRouteImport } from './routes/settings'

const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimesTypeNameRoute = RuntimesTypeNameRouteImport.update({
  id: '/runtimes/$typeName',
  path: '/runtimes/$typeName',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimesTypeNameInstanceNameRoute =
  RuntimesTypeNameInstanceNameRouteImport.update({
    id: '/$instanceName',
    path: '/$instanceName',
    getParentRoute: () => RuntimesTypeNameRoute,
  } as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/queue': typeof QueueRoute
  '/runtimes/$typeName': typeof RuntimesTypeNameRouteWithChildren
  '/runtimes/$typeName/$instanceName': typeof RuntimesTypeNameInstanceNameRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/queue': typeof QueueRoute
  '/runtimes/$typeName': typeof RuntimesTypeNameRouteWithChildren
  '/runtimes/$typeName/$instanceName': typeof RuntimesTypeNameInstanceNameRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/queue': typeof QueueRoute
  '/runtimes/$typeName': typeof RuntimesTypeNameRouteWithChildren
  '/runtimes/$typeName/$instanceName': typeof RuntimesTypeNameInstanceNameRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/queue'
    | '/runtimes/$typeName'
    | '/runtimes/$typeName/$instanceName'
    | '/sessions/$sessionId'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/queue'
    | '/runtimes/$typeName'
    | '/runtimes/$typeName/$instanceName'
    | '/sessions/$sessionId'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/queue'
    | '/runtimes/$typeName'
    | '/runtimes/$typeName/$instanceName'
    | '/sessions/$sessionId'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  QueueRoute: typeof QueueRoute
  RuntimesTypeNameRoute: typeof RuntimesTypeNameRouteWithChildren
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtimes/$typeName': {
      id: '/runtimes/$typeName'
      path: '/runtimes/$typeName'
      fullPath: '/runtimes/$typeName'
      preLoaderRoute: typeof RuntimesTypeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtimes/$typeName/$instanceName': {
      id: '/runtimes/$typeName/$instanceName'
      path: '/$instanceName'
      fullPath: '/runtimes/$typeName/$instanceName'
      preLoaderRoute: typeof RuntimesTypeNameInstanceNameRouteImport
      parentRoute: typeof RuntimesTypeNameRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RuntimesTypeNameRouteChildren {
  RuntimesTypeNameInstanceNameRoute: typeof RuntimesTypeNameInstanceNameRoute
}

const RuntimesTypeNameRouteChildren: RuntimesTypeNameRouteChildren = {
  RuntimesTypeNameInstanceNameRoute: RuntimesTypeNameInstanceNameRoute,
}

const RuntimesTypeNameRouteWithChildren =
  RuntimesTypeNameRoute._addFileChildren(RuntimesTypeNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  QueueRoute: QueueRoute,
  RuntimesTypeNameRoute: RuntimesTypeNameRouteWithChildren,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
